# Generated by Django 6.1.1 on 2026-09-28 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160, verbose_name='Họ và tên')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Số điện thoại')),
                ('company', models.CharField(blank=True, max_length=160, verbose_name='Công ty')),
                ('status', models.CharField(choices=[('lead', 'Tiềm năng'), ('active', 'Đang hoạt động'), ('inactive', 'Ngừng hoạt động')], default='lead', max_length=20, verbose_name='Trạng thái')),
                ('source', models.CharField(blank=True, max_length=120, verbose_name='Nguồn khách hàng')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('ai_segment', models.CharField(choices=[('new', 'Khách hàng mới'), ('potential', 'Khách hàng tiềm năng'), ('vip', 'Khách hàng VIP'), ('at_risk', 'Có nguy cơ rời bỏ'), ('unclassified', 'Chưa phân loại')], default='unclassified', max_length=24, verbose_name='Phân khúc AI')),
                ('ai_summary', models.TextField(blank=True, verbose_name='Nhận định AI')),
                ('ai_email_suggestion', models.TextField(blank=True, verbose_name='Email do AI gợi ý')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
            ],
            options={
                'verbose_name': 'Khách hàng',
                'verbose_name_plural': 'Khách hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('classify', 'Phân loại khách hàng'), ('email', 'Gợi ý email')], max_length=20, verbose_name='Tác vụ')),
                ('provider', models.CharField(default='mock', max_length=40, verbose_name='Nhà cung cấp')),
                ('result', models.TextField(verbose_name='Kết quả')),
                ('success', models.BooleanField(default=True, verbose_name='Thành công')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_logs', to='crm.customer', verbose_name='Khách hàng')),
            ],
            options={
                'verbose_name': 'Nhật ký AI',
                'verbose_name_plural': 'Nhật ký AI',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=40, unique=True, verbose_name='Mã đơn')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='Giá trị')),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('processing', 'Đang xử lý'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('order_date', models.DateField(verbose_name='Ngày đặt hàng')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='crm.customer', verbose_name='Khách hàng')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
                'ordering': ['-order_date', '-created_at'],
            },
        ),
    ]
